// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaPl.SKS.DataAccess.Sql;

namespace PaPl.SKS.DataAccess.Sql.Migrations
{
    [DbContext(typeof(SQLDataContext))]
    [ExcludeFromCodeCoverage]
    partial class SQLDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaPl.SKS.DataAccess.Entities.Hop", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HopType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProcessingDelayMins")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("Hop");
                });

            modelBuilder.Entity("PaPl.SKS.DataAccess.Entities.HopArrival", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParcelTrackingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParcelTrackingId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Code");

                    b.HasIndex("ParcelTrackingId");

                    b.HasIndex("ParcelTrackingId1");

                    b.ToTable("HopArrival");
                });

            modelBuilder.Entity("PaPl.SKS.DataAccess.Entities.Parcel", b =>
                {
                    b.Property<string>("TrackingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("RecipientId")
                        .HasColumnType("int");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int");

                    b.Property<int?>("State")
                        .HasColumnType("int");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("TrackingId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("Parcel");
                });

            modelBuilder.Entity("PaPl.SKS.DataAccess.Entities.Recipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipient");
                });

            modelBuilder.Entity("PaPl.SKS.DataAccess.Entities.HopArrival", b =>
                {
                    b.HasOne("PaPl.SKS.DataAccess.Entities.Parcel", null)
                        .WithMany("FutureHops")
                        .HasForeignKey("ParcelTrackingId");

                    b.HasOne("PaPl.SKS.DataAccess.Entities.Parcel", null)
                        .WithMany("VisitedHops")
                        .HasForeignKey("ParcelTrackingId1");
                });

            modelBuilder.Entity("PaPl.SKS.DataAccess.Entities.Parcel", b =>
                {
                    b.HasOne("PaPl.SKS.DataAccess.Entities.Recipient", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId");

                    b.HasOne("PaPl.SKS.DataAccess.Entities.Recipient", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PaPl.SKS.DataAccess.Entities.Parcel", b =>
                {
                    b.Navigation("FutureHops");

                    b.Navigation("VisitedHops");
                });
#pragma warning restore 612, 618
        }
    }
}
